# -*- coding: utf-8 -*-
"""Вышмат ДЗ 3

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jJPJBN1TO60Qzr7yV2t-Ae1yET7vUXdK
"""

import numpy as np
from scipy.optimize import minimize

def normal_pdf(t, p):
  mu, sigma = p
  nominator = np.exp(-((t - mu) ** 2 / (2 * sigma ** 2)))
  denominator = sigma * np.sqrt(2 * np.pi)

  return nominator / denominator

def MLE(pdf_func, x, p0):
  def nll_internal(p): # negative log-likelyhood
    densities = pdf_func(x, p)
    if np.any(densities <= 0):
      return np.inf
    return -np.sum(np.log(densities))

  bounds = [(None, None), (0.001, None)]

  res = minimize(fun=nll_internal, x0=p0, method='L-BFGS-B', bounds=bounds)
  p_est = res.x
  return p_est

np.random.seed(52)
true_mu = 5.0
true_sigma = 2.0

sample = np.random.normal(loc=true_mu, scale=true_sigma, size=1000)

print(MLE(normal_pdf, sample, [np.mean(sample), np.std(sample)]))